name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

env:
  FORCE_COLOR: true

jobs:
  release:
    name: Changelog PR or Release
    if: ${{ github.repository_owner == 'moqtail' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    environment:
      name: npm
      url: https://www.npmjs.com/package/moqtail
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures

      - name: Cache Rust Workspace
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build -p moqtail --release

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run changeset:release
          commit: 'ci: release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
